### ISSUE TITLE
Needs a timeout

### ISSUE THREAD

**Issue by rpn0709** [narbehaj/ssl-checker#10]
I have a list of domains i'm iterating through and it gets stuck on a few because of no timeout.

**Comment by narbehaj** [comment]
Thank you so much for the feedback. Are you running the script via `-a` parameter?

**Comment by hhtsoi-acoustic** [comment]
socket.setdefaulttimeout(timeout) in     def get_cert(self, host, port, user_args): would probably help.
ie,   socket.setdefaulttimeout(60) or even 10 would speed it up
