### ISSUE TITLE
Analyze doesn't seem to work

### ISSUE THREAD

**Issue by rpn0709** [narbehaj/ssl-checker#11]
I would expect to see something comeback when the SAN is mismatched but I don't see anything. Great work though!

**Comment by narbehaj** [comment]
Thanks, would you be more specific? Or you might give me an overview of what you are looking for?

**Comment by rpn0709** [comment]
I'm using the json output. It seems analyze doesn't work with it. Also moving the hostname inside the document would be more useful, root doc should just see message or host, reason being is if you were to index it into something like elasticsearch you don't want the dynamic naming.

**Comment by tcpzix** [comment]
great work
how can i save the show_result in a variable ? 
when i do <x = ssl.show_result(ssl.get_args(json_args=args)> the result just print out in terminal and x doesn't get any value or type!
thanks

**Comment by narbehaj** [comment]
> great work
> how can i save the show_result in a variable ?
> when i do <x = ssl.show_result(ssl.get_args(json_args=args)> the result just print out in terminal and x doesn't get any value or type!
> thanks

Fixed in the last commit, please pull.

**Comment by summersonne** [comment]
SSLChecker.show_result(SSLChecker.get_args(json_args=args))
TypeError: get_args() missing 1 required positional argument: 'self'

Can you help, please?

**Comment by narbehaj** [comment]
@summersonne can you print your `args` here?

**Comment by summersonne** [comment]
args = {
    'hosts': ['google.com', 'cisco.com']
  }

**Comment by narbehaj** [comment]
@summersonne mine works fine in both python2 and 3. Could you send your whole script via email, please?
