### ISSUE TITLE
have connection attempt failed issue due to Timeout

### ISSUE THREAD

**Issue by XinCai** [narbehaj/ssl-checker#13]
C:\dev\pythonscript\ssl-checker>python ssl_checker.py -H xxx.com
+---------------------+
| Analyzing 1 host(s) |
+---------------------+
        [31m[-][39m bamboo.icare.nsw.gov.au Failed: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond

+------------------------------------------------------+
| Successful: 0 | Failed: 1 | Duration: 0:00:21.100594 |
+------------------------------------------------------+

can you please help ?

**Comment by narbehaj** [comment]
It seems it might be your network connection, I got it. Can you check with another network?

```
(01:06:00) narbeh@narbeh-xps:~/Desktop/Shared_DIR/Scripts/ssl-checker$ python3 ssl_checker.py -H bamboo.icare.nsw.gov.au
+---------------------+
| Analyzing 1 host(s) |
+---------------------+
	[+] bamboo.icare.nsw.gov.au
	----------------------------
		Issued domain: *.icare.nsw.gov.au
		Issued to: Insurance and Care NSW
		Issued by: DigiCert Inc (US)
		Valid from: 2019-07-27
		Valid to: 2021-10-26 (580 days left)
		Validity days: 822
		Certificate S/N: 16646346723938866779640511686477694943
		Certificate SHA1 FP: 19:8A:FC:CA:0D:EA:FE:E2:1B:9F:B0:7C:82:39:88:7B:7D:00:56:D1
		Certificate version: 2
		Certificate algorithm: sha256WithRSAEncryption
		Expired: False
		Certificate SAN's: 
		 \_ DNS:*.icare.nsw.gov.au
		 \_ DNS:icare.nsw.gov.au


+------------------------------------------------------+
| Successful: 1 | Failed: 0 | Duration: 0:00:01.465114 |
+------------------------------------------------------+
```
