### ISSUE TITLE
SSLV3 fails with unexpected EOF

### ISSUE THREAD

**Issue by rpn0709** [narbehaj/ssl-checker#16]
When scanning older websites that don't have TLS 1.1 or up available they fail with 'Unexpected EOF.' It would be nice if this would fail without this error and report with analyze and proper json if using that syntax.

**Comment by narbehaj** [comment]
Sure. Thanks. I'll check ASAP

**Comment by narbehaj** [comment]
Can I have a sample domain?

**Comment by rpn0709** [comment]
www.aerotraininc.com

**Comment by narbehaj** [comment]
Thanks, fixed.
