### ISSUE TITLE
analyze doesn't return analysis

### ISSUE THREAD

**Issue by DannyCork** [narbehaj/ssl-checker#18]
I ran a scan specifying-a
```
$ ./ssl_checker.py -H www.daft.ie -a 
+---------------------+
| Analyzing 1 host(s) |
+---------------------+
Warning: -a/--analyze is enabled. It takes more time...

	[+] www.daft.ie
	----------------
		Issued domain: *.daft.ie
		Issued to: None
		Issued by: DigiCert Inc (US)
		Valid from: 2020-03-02
		Valid to: 2021-03-28 (277 days left)
		Validity days: 391
		Certificate S/N: 11460648071364235415320376872911043945
		Certificate SHA1 FP: D2:38:E6:55:EF:99:C7:1C:27:C6:64:09:CE:78:EB:20:87:1B:B5:AA
		Certificate version: 2
		Certificate algorithm: sha256WithRSAEncryption
		Expired: False
		Certificate SAN's: 
		 \_ DNS:*.daft.ie
		 \_ DNS:daft.ie


+------------------------------------------------------+
| Successful: 1 | Failed: 0 | Duration: 0:00:01.645121 |
```
Using the -a doesn't return 
- Certificate grade: 
- Poodle vulnerability: 
- Heartbleed vulnerability: 
- Hearbeat vulnerability: 
- Freak vulnerability: 
- Logjam vulnerability: 
- Drown vulnerability: 

comparing this to the Qualys report for the same domain
![image](https://user-images.githubusercontent.com/3512672/85410058-8324c600-b55e-11ea-8c7e-cf874449a6e7.png)
![image](https://user-images.githubusercontent.com/3512672/85410392-ef9fc500-b55e-11ea-88e2-4166f4dac62d.png)

**Comment by DannyCork** [comment]
I also observed this while testing with a different domain ./ssl_checker.py -H hoeilaart.be -a

**Comment by narbehaj** [comment]
Thanks for reporting, pull the latest commit and test again.

**Comment by DannyCork** [comment]
Solved. Thanks!
