### ISSUE TITLE
anyway to just print summary of valid, warning, expired

### ISSUE THREAD

**Issue by hhtsoi-acoustic** [narbehaj/ssl-checker#19]
The goal is to have a check run once per day, and if you have like 500 ssl domains to check, it would just output something like:

ssl_checker.py  -f /tmp/domains.txt --summary

| Successful: 7 | Failed: 3 | Valid: 100| Warning: 100| Expired: 10 | Duration: 0:00:01.991176 |

**Comment by narbehaj** [comment]
Perfect! I'll get back to this issue soon after checking how can we cover that.

**Comment by narbehaj** [comment]
Done. Please check the last commit.
