### ISSUE TITLE
How to use the Python Module

### ISSUE THREAD

**Issue by selloween** [narbehaj/ssl-checker#20]
Hi,

First of all thanks for this awesome project.

This isn't really a issue, but I'm having trouble with passing arguments when importing  ssl_checker as Python Module. 
I would like to make ssl checks from within a flask app. I guess I would have to pass a dictionary like the code below. How would the dictionary structure have to look like? (Sorry - I'm new to Python and this might be a really stupid question to ask)

```python
@app.route('/test', methods=['GET'])
def test():
    SSLCheckerObject = SSLChecker()
    args = {
            'hosts': 'github.com'
    }
    return SSLCheckerObject.show_result(args)
```
I get following error:
```
AttributeError: 'dict' object has no attribute 'hosts'
```

Any help would be really appreciated.

Cheers,

Selloween

**Comment by narbehaj** [comment]
Hey, thank you for using this tool.

I check and pushed the new code. Please do a `git pull`.

This is how it works now:

```
from ssl_checker import SSLChecker

SSLChecker = SSLChecker()
args = {
    'hosts': ['google.com', 'cisco.com']
}

SSLChecker.show_result(SSLChecker.get_args(json_args=args))
```

**Comment by selloween** [comment]
Hi, That's awesome. Thank you! :-)
