### ISSUE TITLE
[Suggestion] Return result in JSON

### ISSUE THREAD

**Issue by mzulfahmy** [narbehaj/ssl-checker#3]
Hi,

Just some suggestion, let say i'm calling scan.sslscan(domain) and it will return in json format.

Example :

```
from sslchecker import sslscan

scan.sslscan(domain)
return json
```

There is any idea for this enhancement?

Thanks

**Comment by DannyCork** [comment]
excellent idea :)

**Comment by jpmens** [comment]
I too would like to see this. `ssl-checker` seems to do a very good job and it's ideal to integrate into a number of monitoring scripts (Nagios, Icinga, Zabbix).

**Comment by narbehaj** [comment]
Fixed in the last commit
