### ISSUE TITLE
-a analyse security scans not completing

### ISSUE THREAD

**Issue by DannyCork** [narbehaj/ssl-checker#5]
So I ran 
```
$ssl-checker root# python3.7 ssl_checker.py -H independent.ie  -p -a
+---------------------+
| Analyzing 1 host(s) |
+---------------------+
Warning: -a/--analyze is enabled. It takes more time...

Analyzing the security of gov.ie. Please wait..
```

10 minutes later sslchecker is still checking. I tried multiple domains, none of them appear to finish :( If I do a regular scan without the -a iit finishes almost straight away 

How long should a -a analyse security scan take?

**Comment by DannyCork** [comment]
I opened a new terminal and I couldn't recreate the problem.
Closing.

**Comment by DannyCork** [comment]
I added some debugging code to output the content of main_request.
The reason the request never finishes is because status': 'IN_PROGRESS' is always True.

**Comment by DannyCork** [comment]
It appears the sslchecker code is correct, this request is taking forever on ssllabs:

https://www.ssllabs.com/ssltest/analyze.html?d=independent.ie&hideResults=on&latest

**Comment by narbehaj** [comment]
Hi,

Yes, the issue is related to SSL Labs, check here to see how it works. 
https://api.ssllabs.com/api/v3/analyze?host=independent.ie

If you know any other good service let me know. Thanks
