### ISSUE TITLE
Neither option --json nor --pretty produce JSON

### ISSUE THREAD

**Issue by jpmens** [narbehaj/ssl-checker#6]
The help says that `--pretty` or `-p` "print indented and human readable JSON", but unfortunately that's not JSON:

```bash
./ssl_checker.py -j -p -H google.com | python -mjson.tool
Expecting property name enclosed in double quotes: line 1 column 2 (char 1)
```

The code uses `print()` respectively `pprint()` and those don't do JSON.

**Comment by narbehaj** [comment]
Thanks, I'll look into this.

**Comment by narbehaj** [comment]
Thanks for the PR :)

**Comment by narbehaj** [comment]
I edited the `pprint` part so we will have the pretty print, but your code which used `json.dumps()` is still there.

**Comment by jpmens** [comment]
Unfortunately that once again breaks JSON:

```
./ssl_checker.py -j -p -H google.de | python -mjson.tool
Expecting property name: line 1 column 2 (char 1)
```

`pprint()` does not produce pretty JSON; it produces pretty "something", but that's not JSON :-)

**Comment by jpmens** [comment]
The reason I used

```python
print(json.dumps(context, indent=4))
```

was to have "pretty-printed", i.e. indented JSON output.

**Comment by narbehaj** [comment]
Yes, exactly I know what you were looking for. If someone needs a pure JSON so he can use `-j` only, for pretty JSON then they can add `-p`. But for the pipe I see you that you need, `-j` only will work for you. Isn't it?

**Comment by jpmens** [comment]
I don't have a problem with `-j`, but IMO the term "pretty JSON" should be removed from the documentation as it is not JSON.

But, to be honest, I don't understand the unwillingness of creating proper "pretty" JSON. :) 

Put differently: why do you prefer pprint()'s output?

**Comment by narbehaj** [comment]
I agree, let's remove the `-p` at all. If it's JSON, it should be in the standard format. So no other formatting.

**Comment by jpmens** [comment]
The formatting (white space) isn't the issue. The issue is that `pprint()` produces strings in single quotes whereas JSON expect double quotes. `json.dumps()` handles that correctly.

**Comment by narbehaj** [comment]
It's done. Thanks for your contribution.
